# Configuration file for examples/3PMD/Prediction/Rectangle/NN/Regression/main.py

RANDOM_SEED: 42

BATCH_SIZE: 64
EPOCHS: 150
PATIENCE: 10
WEIGHT_DEC: 1e-5
LEARN_RATE: 1e-5
HIDDEN_SIZE: 2048

DO_TRAINING: false
TRIG_FUNCS: true  
USE_ONLY_CPU: false
EXPORT_TO_ONNX: false

DATASET: /home/enrico.saccon/mpdp_new/new_rect.csv

# OUTPUT_MODEL_PATH: /home/enrico.saccon/mpdp_new/sbatch/regression/models
OUTPUT_MODEL_NAME: /home/enrico.saccon/mpdp_new/sbatch/regression/models/model_regression_55993.pt
PLOT_PATH: /home/enrico.saccon/mpdp_new/sbatch/regression/plots

# Model 
LAYERS:
  - Linear(in_size, hid_size // 2)
  - ReLU()
  - Dropout(0.1)
  - Linear(hid_size // 2, hid_size)
  - LeakyReLU()
  - Linear(hid_size, hid_size)
  - LeakyReLU()
  - Linear(hid_size, hid_size // 2)
  - ReLU()
  - Linear(hid_size // 2, out_size)